services:
  db:
    image: postgres:14-alpine
    container_name: offer_manager_db
    restart: always
    environment:
      POSTGRES_DB: offer_manager_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5440:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - offer_manager_net
    volumes:
      # üö® 1. VOLUMEN PERSISTENTE: Asegura que los datos no se borren.
      - postgres_data:/var/lib/postgresql/data 
      # üö® 2. INICIALIZACI√ìN DE ESQUEMA: Monta tus scripts SQL aqu√≠.
      - ./db/init:/docker-entrypoint-initdb.d 

  app:
    image: 120569610818.dkr.ecr.us-east-1.amazonaws.com/cdk-exp-container-assets-120569610818-us-east-1:699775ffb48570c925437c99410c5f5637930979-offer_manager
    container_name: offer_manager
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: offer_manager_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      PGSSLMODE: disable
      DB_SSLMODE: disable
      # URL del microservicio de products dentro de su red existente
      PRODUCTS_SERVICE_URL: http://MediSu-MediS-5XPY2MhrDivI-109634141.us-east-1.elb.amazonaws.com/
      ORDERS_SERVICE_URL: http://MediSu-MediS-5XPY2MhrDivI-109634141.us-east-1.elb.amazonaws.com/
      PRODUCTS_SERVICE_TIMEOUT: 10
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    ports:
      - "8080:8080"
    networks:
      - offer_manager_net
      - products_default

# üö® 3. DEFINICI√ìN DEL VOLUMEN (NIVEL RA√çZ) üö®
volumes:
  postgres_data:

# üö® 4. DEFINICI√ìN DE REDES (NIVEL RA√çZ) üö®
# Esto resuelve el error "undefined network offer_manager_net".
networks:
  offer_manager_net:
    driver: bridge
  products_default:
    external: true
