services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: products
    environment:
      DB_HOST: host.docker.internal      # ðŸ‘ˆ nombre del contenedor de tu DB ya existente
      DB_PORT: 5434
      DB_NAME: medisupplydb
      DB_USER: postgres
      DB_PASSWORD: postgres
      CACHE_DB: 0
      CACHE_HOST: med-me-mrp9qeogurvj.ozabfh.0001.use1.cache.amazonaws.com
      CACHE_PORT: 6379
      RUN_DB_INIT_ON_STARTUP: "True"
    ports:
      - "8081:8080"
    command: ["sh", "-c", "sleep 5 && python app.py"]
    networks:
      - products_default   # ðŸ‘ˆ usa la red donde ya estÃ¡ tu DB

networks:
  products_default:
    external: true         # ðŸ‘ˆ le decimos a Compose que la red ya existe
